softclient4es {
  license {
    key = ""
    key = ${?SOFTCLIENT4ES_LICENSE_KEY}
    api-key = ""
    api-key = ${?SOFTCLIENT4ES_API_KEY}
    api-url = "https://license.softclient4es.com"
    connect-timeout = 10s
    read-timeout = 10s

    refresh {
      enabled = true
      interval = 24h
    }

    telemetry {
      enabled = true
    }

    grace-period = 14d

    cache-dir = ${user.home}/.softclient4es
  }
}
