# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release
# Run workflow on commits to the `main` branch
on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
#      - '*'         # matches every branch that doesn't contain a '/'
#      - '*/*'       # matches every branch containing a single '/'
#      - '**'        # matches every branch
#      - '!main'     # excludes main  

permissions:
  contents: read

jobs:
  release:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - name: Env
      run: |
        echo "JFROG_USER=${{ secrets.JFROG_USER }}" >>  $GITHUB_ENV
        echo "JFROG_PASSWORD=${{ secrets.JFROG_PASSWORD }}" >>  $GITHUB_ENV
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >>  $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
#        cache: 'sbt'
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Formatting
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
    - name: Set vm.max_map_count
      run: sudo sysctl -w vm.max_map_count=262144
    - name: Run tests & Coverage Report
      run: SBT_OPTS="-Xss4M -Xms1g -Xmx4g -Dfile.encoding=UTF-8" sbt coverage test coverageReport coverageAggregate
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: sql/target/scala-2.13/coverage-report/cobertura.xml,client/testkit/target/scala-2.13/coverage-report/cobertura.xml,java/testkit/target/scala-2.13/coverage-report/cobertura.xml,persistence/target/scala-2.13/coverage-report/cobertura.xml,teskit/target/scala-2.13/coverage-report/cobertura.xml
        flags: unittests
        fail_ci_if_error: false
        verbose: true
    - name: Publish
      run: SBT_OPTS="-Xss4M -Xms1g -Xmx4g -Dfile.encoding=UTF-8" sbt publish
